# Generated by Django 4.2.4 on 2023-09-21 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_data', '0002_alignment'),
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='alignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dnd_data.alignment'),
            preserve_default=False,
        ),
    ]
