# Generated by Django 4.2.4 on 2023-09-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_alter_character_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deceased', 'Deceased')], default='active', max_length=20),
        ),
    ]
