# Generated by Django 4.2.4 on 2023-10-08 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_data', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.AlterModelOptions(
            name='ability',
            options={'verbose_name_plural': 'Abilities'},
        ),
    ]
