# Generated by Django 4.2.4 on 2023-09-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
