# Generated by Django 4.2.4 on 2023-10-08 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_data', '0002_delete_attribute_alter_ability_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='ability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dnd_data.ability'),
        ),
    ]
