# Generated by Django 4.2.4 on 2023-10-08 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_data', '0003_skill_ability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='ability',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='dnd_data.ability'),
            preserve_default=False,
        ),
    ]
