# Generated by Django 4.2.4 on 2023-10-08 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_data', '0004_alter_skill_ability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='ability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ability_skills', to='dnd_data.ability'),
        ),
    ]
