# Generated by Django 4.2.4 on 2023-10-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_data', '0005_alter_skill_ability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='speed',
            field=models.IntegerField(default=6),
        ),
    ]
