# Generated by Django 4.2.4 on 2023-11-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0019_alter_inventoryitem_item_delete_item_delete_tag'),
        ('dnd_data', '0011_alter_item_allowed_characters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='allowed_characters',
            field=models.ManyToManyField(blank=True, related_name='accessible_items', to='campaigns.character'),
        ),
    ]
