# Generated by Django 4.2.4 on 2023-11-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_data', '0013_spellcomponent_spellschool_spelltype_weapon_spell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='type',
        ),
        migrations.AddField(
            model_name='spell',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='SpellType',
        ),
    ]
