# Generated by Django 4.2.4 on 2023-11-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_data', '0014_remove_spell_type_spell_level_delete_spelltype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alignment',
            name='created',
        ),
        migrations.RemoveField(
            model_name='background',
            name='created',
        ),
        migrations.RemoveField(
            model_name='characterclass',
            name='created',
        ),
        migrations.RemoveField(
            model_name='race',
            name='created',
        ),
    ]
