# Generated by Django 4.2.4 on 2023-11-15 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_data', '0017_damagetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='damage_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dnd_data.damagetype'),
            preserve_default=False,
        ),
    ]
