# Generated by Django 4.2.4 on 2023-10-08 07:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dnd_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dungeon_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField(default=1)),
                ('max_health', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_health', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('proficiency_bonus', models.PositiveIntegerField(default=0)),
                ('inspiration', models.BooleanField(default=False)),
                ('initiative', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deceased', 'Deceased')], default='inactive', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('alignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_data.alignment')),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_data.background')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_data.characterclass')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_data.race')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('proficiency', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_skills', to='campaigns.character')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_data.skill')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('modifier', models.IntegerField(default=0)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_data.ability')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_attributes', to='campaigns.character')),
            ],
            options={
                'unique_together': {('character', 'ability')},
            },
        ),
    ]
