# Generated by Django 4.2.4 on 2023-09-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='characters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(default='Campaign description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='dungeon_master',
            field=models.CharField(default='Matej', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(default="Matej's Campaign", max_length=200),
            preserve_default=False,
        ),
    ]
