# Generated by Django 4.2.4 on 2023-09-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_character_status'),
        ('campaigns', '0002_alter_campaign_characters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='characters.character'),
        ),
    ]
