# Generated by Django 4.2.4 on 2023-10-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_characterability_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterskill',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
