# Generated by Django 4.2.4 on 2023-10-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_characterskill_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterability',
            name='auto_calculate',
            field=models.BooleanField(default=True),
        ),
    ]
