# Generated by Django 4.2.4 on 2023-10-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_characterability_auto_calculate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterskill',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
