# Generated by Django 4.2.4 on 2023-10-08 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_alter_characterskill_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterability',
            options={'verbose_name_plural': 'Character Abilities'},
        ),
        migrations.RemoveField(
            model_name='characterability',
            name='auto_calculate',
        ),
    ]
