# Generated by Django 4.2.4 on 2023-10-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_alter_characterability_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='speed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
