# Generated by Django 4.2.4 on 2023-10-09 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_data', '0006_alter_race_speed'),
        ('campaigns', '0008_savingthrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassiveSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('proficiency', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passive_skills', to='campaigns.character')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_data.skill')),
            ],
        ),
    ]
