# Generated by Django 4.2.4 on 2023-10-10 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_data', '0007_dice'),
        ('campaigns', '0009_passiveskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='armor_class',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='heavy_armor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='light_armor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='middle_armor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='shields',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HitDice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_qty', models.PositiveIntegerField(default=0)),
                ('actual_qty', models.PositiveBigIntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hit_dices', to='campaigns.character')),
                ('dice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_data.dice')),
            ],
        ),
    ]
