# Generated by Django 4.2.4 on 2023-10-10 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_character_armor_class_character_heavy_armor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('max_slots', models.PositiveIntegerField(default=0)),
                ('remaining_slots', models.PositiveIntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spell_slots', to='campaigns.character')),
            ],
        ),
    ]
