# Generated by Django 4.2.4 on 2023-10-10 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_data', '0007_dice'),
        ('campaigns', '0011_spellslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='magical_property',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='dnd_data.ability'),
        ),
        migrations.AlterUniqueTogether(
            name='spellslot',
            unique_together={('character', 'level')},
        ),
    ]
