# Generated by Django 4.2.4 on 2023-10-30 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_data', '0007_dice'),
        ('campaigns', '0013_remove_character_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterability',
            options={'verbose_name_plural': 'Character abilities'},
        ),
        migrations.AlterUniqueTogether(
            name='characterskill',
            unique_together={('character', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='hitdice',
            unique_together={('character', 'dice')},
        ),
        migrations.AlterUniqueTogether(
            name='passiveskill',
            unique_together={('character', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='savingthrow',
            unique_together={('character', 'ability')},
        ),
        migrations.CreateModel(
            name='CharacterMultiClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_classes', to='campaigns.character')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_data.characterclass')),
            ],
            options={
                'verbose_name_plural': 'Character MultiClasses',
                'unique_together': {('character', 'character_class')},
            },
        ),
    ]
