# Generated by Django 4.2.4 on 2023-10-30 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_alter_characterability_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='character_class',
        ),
    ]
