# Generated by Django 4.2.4 on 2023-11-01 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_alter_inventory_options_alter_inventory_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='attunement',
        ),
        migrations.RemoveField(
            model_name='item',
            name='qty',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='attunement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='qty',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='campaigns.tag'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='campaigns.character'),
        ),
        migrations.DeleteModel(
            name='ItemTag',
        ),
    ]
