# Generated by Django 4.2.4 on 2023-11-01 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_data', '0008_tag_item'),
        ('campaigns', '0018_remove_item_attunement_remove_item_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_data.item'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
