# Generated by Django 4.2.4 on 2023-11-01 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_data', '0013_spellcomponent_spellschool_spelltype_weapon_spell'),
        ('campaigns', '0019_alter_inventoryitem_item_delete_item_delete_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.character')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_data.spell')),
            ],
        ),
    ]
