# Generated by Django 4.2.4 on 2023-11-01 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_data', '0013_spellcomponent_spellschool_spelltype_weapon_spell'),
        ('campaigns', '0020_characterspell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='level',
        ),
        migrations.AddField(
            model_name='character',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='charactermulticlass',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='characterspell',
            name='prepared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='characterspell',
            name='spellcasting_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dnd_data.characterclass'),
        ),
        migrations.AlterUniqueTogether(
            name='characterspell',
            unique_together={('character', 'spell')},
        ),
    ]
