# Generated by Django 4.2.4 on 2023-11-01 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0021_remove_character_level_character_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterspell',
            name='spellcasting_class',
        ),
        migrations.AddField(
            model_name='characterspell',
            name='character_class_relation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='known_spells', to='campaigns.charactermulticlass'),
            preserve_default=False,
        ),
    ]
