# Generated by Django 4.2.4 on 2023-11-01 22:45

from django.db import migrations, models
import django.db.models.deletion
from datetime import date


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0022_remove_characterspell_spellcasting_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.DateField(default=date.today),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SessionCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.character')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_characters', to='campaigns.session')),
            ],
            options={
                'unique_together': {('session', 'character')},
            },
        ),
    ]
