# Generated by Django 4.2.4 on 2023-11-01 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0023_session_date_sessioncharacter'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_sessions', to='campaigns.campaign'),
            preserve_default=False,
        ),
    ]
