# Generated by Django 4.2.4 on 2023-11-15 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0025_characterweapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='magical_attack_bonus',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='characterspell',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_spells', to='campaigns.character'),
        ),
    ]
