# Generated by Django 4.2.4 on 2023-11-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0026_character_magical_attack_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterweapon',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
